# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnderTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnderTimes

	pod 'Alamofire', '~> 4.9.1'
	pod 'ObjectMapper', '~> 3.5'
	pod 'AlamofireObjectMapper'
	pod 'Apollo'
  target 'UnderTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnderTimesUITests' do
    # Pods for testing
  end

end
